import JSZip from 'jszip';

const PBI_PAGE_W = 1280;
const PBI_PAGE_H = 720;

const TYPE_MAP = {
  bar:     'barChart',
  line:    'lineChart',
  area:    'areaChart',
  kpi:     'kpi',
  donut:   'donutChart',
  scatter: 'scatterChart',
  table:   'tableEx',
};

/**
 * Exports visuals as a zip of PBIP-compatible visual.json files.
 *
 * Output structure:
 *   visuals/
 *     <visual-id>/visual.json   ← drop into your PBIP project's
 *                                  definition/pages/<PageName>/visuals/
 *     README.md
 *
 * @param {Array}  visuals
 * @param {object} designSystem
 * @returns {Promise<Blob>}
 */
export async function exportPBIPVisuals(visuals, designSystem) {
  const readyVisuals = visuals.filter(v => v.status === 'ready' && v.spec);
  if (!readyVisuals.length) throw new Error('No ready visuals to export');

  // Normalise canvas coords → 1280×720 PBI page
  let minX = Infinity, minY = Infinity, maxX = -Infinity, maxY = -Infinity;
  for (const v of readyVisuals) {
    minX = Math.min(minX, v.x);
    minY = Math.min(minY, v.y);
    maxX = Math.max(maxX, v.x + v.width);
    maxY = Math.max(maxY, v.y + v.height);
  }
  const contentW = maxX - minX || PBI_PAGE_W;
  const contentH = maxY - minY || PBI_PAGE_H;
  const scale = Math.min(PBI_PAGE_W / contentW, PBI_PAGE_H / contentH, 1);

  const zip = new JSZip();
  const folder = zip.folder('visuals');

  for (const v of readyVisuals) {
    const px = Math.round((v.x - minX) * scale);
    const py = Math.round((v.y - minY) * scale);
    const pw = Math.round(v.width  * scale);
    const ph = Math.round(v.height * scale);

    const pbiType = TYPE_MAP[v.spec.visualType] || TYPE_MAP[v.visualType] || 'barChart';

    const dataColors = (v.spec.series || []).map(s => ({
      solid: { color: s.color || '#0078D4' },
    }));

    const visualJson = {
      $schema: 'https://developer.microsoft.com/json-schemas/fabric/item/report/definition/visualContainer/1.0.0/schema.json',
      name: v.id,
      position: {
        x: px, y: py,
        width: pw, height: ph,
        z: v.zIndex || 1,
        tabOrder: 0,
      },
      visual: {
        visualType: pbiType,
        query: { queryState: {} },
        objects: {
          ...(dataColors.length && { dataColors }),
          background: {
            show: [{ conditions: [], value: { expr: { Literal: { Value: 'true' } } } }],
            color: [{ conditions: [], value: { expr: { Literal: { Value: `'${designSystem.background || '#ffffff'}'` } } } }],
          },
        },
        vcObjects: {
          title: {
            properties: {
              text: { expr: { Literal: { Value: `'${(v.spec.title || v.name || '').replace(/'/g, "\\'")}′` } } },
            },
          },
        },
      },
    };

    folder.folder(v.id).file('visual.json', JSON.stringify(visualJson, null, 2));
  }

  folder.file('README.md', buildReadme(readyVisuals, designSystem));

  return zip.generateAsync({ type: 'blob', mimeType: 'application/zip' });
}

function buildReadme(visuals, ds) {
  return [
    `# PBIP Visual Definitions`,
    ``,
    `Generated by **${ds.name || 'PBI Design Moodboard'}** on ${new Date().toLocaleDateString()}.`,
    ``,
    `## How to use`,
    ``,
    `1. Open your Power BI project folder (ends in \`.Report\`)`,
    `2. Navigate to \`definition/pages/<YourPage>/visuals/\``,
    `3. Copy each \`<visual-id>/\` folder from this zip into that directory`,
    `4. Reload in Power BI Desktop — visuals appear at their positions`,
    `5. Replace placeholder queries with your real data fields`,
    ``,
    `Visual positions are normalised to **1280 × 720**. Set your page to this size in PBI: View → Page view → Page size → Custom.`,
    ``,
    `## Visuals`,
    ``,
    ...visuals.map(v => [
      `### ${v.spec.title || v.name}`,
      `- **Type:** \`${v.spec.visualType}\``,
      `- **ID:** \`${v.id}\``,
      v.description ? `- **Prompt:** ${v.description}` : null,
      ``,
    ].filter(Boolean).join('\n')),
  ].join('\n');
}
